TARGET := test

INCLUDE	:=	include
SOURCE	:=	source

ICON_JPG	:=	icon.jpg
NACP_JSON	:=	nacp.json

TARGET_MODE	:=	NRO

BIOSPHERE_ROOT := $(CURDIR)/../Biosphere

include $(BIOSPHERE_ROOT)/compile/Target.mk

clean: clean_target