TARGET := rom

INCLUDE	:=	include include/sys
SOURCE	:=	source source/quickjs

ICON_JPG	:=	icon.jpg
NACP_JSON	:=	nacp.json
ROMFS_DIR	:=	romfs

TARGET_MODE	:=	NRO

include $(BIOSPHERE_ROOT)/compile/Target.mk

clean: clean_target